#!/bin/bash

# HG680P GPIO Wrapper
# by Lutfa Ilham
# v1.0
# Revisi by reyre
# GPIO founder for AX810/AT01 By reyre

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

GPIO="/sys/class/gpio"

function dual_general() {
  pin_on="${2}"
  pin_off="${3}"
  # initialize gpio
  echo "${pin_on}" > "${GPIO}/export"
  echo "${pin_off}" > "${GPIO}/export"
  echo out > "${GPIO}/gpio${pin_on}/direction"
  echo out > "${GPIO}/gpio${pin_off}/direction"
  case "${1}" in
    "on")
      echo 0 > "${GPIO}/gpio${pin_off}/value"
      echo 1 > "${GPIO}/gpio${pin_on}/value"
      ;;
    "off")
      echo 0 > "${GPIO}/gpio${pin_on}/value"
      echo 1 > "${GPIO}/gpio${pin_off}/value"
      ;;
    "warn")
      echo 1 > "${GPIO}/gpio${pin_on}/value"
      echo 1 > "${GPIO}/gpio${pin_off}/value"
      ;;
    "dis")
      echo 0 > "${GPIO}/gpio${pin_on}/value"
      echo 0 > "${GPIO}/gpio${pin_off}/value"
      ;;
  esac
}

function lan() {
  pin_on="552"
  pin_off="551"
  dual_general "${1}" "${pin_on}" "${pin_off}"
}

function usage() {
  cat <<EOF
Usage:
  -lan    [on, off, warn, dis]
EOF
}

case "${1}" in
  -lan)
    lan "${2}"
    ;;
  *)
    usage
    ;;
esac

