#!/bin/bash

clear
(cd /usr/bin && curl -sLko hg680p.sh https://raw.githubusercontent.com/Houjie80/gpio-hg680p/3led/hg680p.sh && chmod +x hg680p.sh)
(cd /usr/bin && curl -sLko inet-hg680p.sh https://raw.githubusercontent.com/Houjie80/gpio-hg680p/3led/inet-hg680p.sh && chmod +x inet-hg680p.sh)
echo " Install selesai"
echo " ketik perintah : inet-hg680p.sh -r"
echo " Untuk Menyalakan LED Internet Indicator"
